work_dir: /home/zhangxuelian/code_wuyushan/wu_aimclr_2.3.0/work_dir/motion_xview/202212201504_draw/linear_eval

weights: /home/zhangxuelian/code_wuyushan/AimCLR/work_dir/motion_xview/202212201504/pretext/epoch300_model.pt
# weights: /data/gty/AAAI_github/ntu60_cv/aimclr_motion/pretext/epoch300_model.pt
ignore_weights: [encoder_q.fc, encoder_k, queue]

# feeder
train_feeder: feeder.ntu_feeder.Feeder_single
train_feeder_args:
  data_path: /home/zhangxuelian/code_wuyushan/wu/data/Base/NTU60_frame50/xview/val_position.npy # train_position.npy
  label_path: /home/zhangxuelian/code_wuyushan/wu/data/Base/NTU-RGB-D/xview/val_label.pkl # train_label.pkl
  shear_amplitude: -1
  temperal_padding_ratio: -1
  mmap: True
test_feeder: feeder.ntu_feeder.Feeder_single
test_feeder_args:
  data_path: /home/zhangxuelian/code_wuyushan/wu/data/Base/NTU60_frame50/xview/val_position.npy
  label_path: /home/zhangxuelian/code_wuyushan/wu/data/Base/NTU-RGB-D/xview/val_label.pkl
  shear_amplitude: -1
  temperal_padding_ratio: -1
  mmap: True

# model
model: net.aimclr.AimCLR
model_args:
  base_encoder: net.st_gcn.Model
  pretrain: False
  # feature_dim: 128
  # queue_size: 32768
  # momentum: 0.999
  # Temperature: 0.07
  # mlp: True
  in_channels: 3
  hidden_channels: 16
  hidden_dim: 256
  num_class: 60
  dropout: 0.5
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'
  supsize: 32768
  edge_importance_weighting: True

# optim
nesterov: False
weight_decay: 0.0
base_lr: 3.
optimizer: SGD
step: [80]

# training
device: [2]  # 3
batch_size: 128  # 128
test_batch_size: 128  # 128
num_epoch: 120
stream: 'motion'

# log
save_interval: -1
eval_interval: 5
